package hesapMakinesi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dkadi
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlScreen = new javax.swing.JPanel();
        txtSonuc = new javax.swing.JTextField();
        pnlControl = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnToplama = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnCikarma = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnCarpma = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnEsittir = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnBolme = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btnNokta = new javax.swing.JButton();
        btnSilme = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hesap Makinesi");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        txtSonuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSonuc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout pnlScreenLayout = new javax.swing.GroupLayout(pnlScreen);
        pnlScreen.setLayout(pnlScreenLayout);
        pnlScreenLayout.setHorizontalGroup(
            pnlScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSonuc)
        );
        pnlScreenLayout.setVerticalGroup(
            pnlScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlScreenLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(txtSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlControl.setLayout(new java.awt.GridLayout(5, 5, 20, 20));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        pnlControl.add(btn7);

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        pnlControl.add(btn8);

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        pnlControl.add(btn9);

        btnToplama.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnToplama.setText("+");
        btnToplama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamaActionPerformed(evt);
            }
        });
        pnlControl.add(btnToplama);

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        pnlControl.add(btn4);

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        pnlControl.add(btn5);

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        pnlControl.add(btn6);

        btnCikarma.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCikarma.setText("-");
        btnCikarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikarmaActionPerformed(evt);
            }
        });
        pnlControl.add(btnCikarma);

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        pnlControl.add(btn1);

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        pnlControl.add(btn2);

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        pnlControl.add(btn3);

        btnCarpma.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCarpma.setText("*");
        btnCarpma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarpmaActionPerformed(evt);
            }
        });
        pnlControl.add(btnCarpma);

        btn0.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        pnlControl.add(btn0);

        btnEsittir.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnEsittir.setText("=");
        btnEsittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsittirActionPerformed(evt);
            }
        });
        pnlControl.add(btnEsittir);

        btnC.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        pnlControl.add(btnC);

        btnBolme.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnBolme.setText("/");
        btnBolme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolmeActionPerformed(evt);
            }
        });
        pnlControl.add(btnBolme);

        btn00.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn00.setText("00");
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        pnlControl.add(btn00);

        btnNokta.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnNokta.setText(".");
        btnNokta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoktaActionPerformed(evt);
            }
        });
        pnlControl.add(btnNokta);

        btnSilme.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSilme.setText("<--");
        btnSilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilmeActionPerformed(evt);
            }
        });
        pnlControl.add(btnSilme);

        btnCE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        pnlControl.add(btnCE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void EnterNumbers(String i){
        String Nums=txtSonuc.getText() + i;
        txtSonuc.setText(Nums);
    }
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("0");
    }                                    

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("1");
    }                                    

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("9");
    }                                    

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("6");
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("7");
    }                                    

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("8");
    }                                    

    private void btnEsittirActionPerformed(java.awt.event.ActionEvent evt) {                                           
     NumEnter2=Double.parseDouble(txtSonuc.getText());
     if(op=="+"){
         Result=NumEnter1+NumEnter2;
         txtSonuc.setText(String.valueOf(Result));
     }
     else if(op=="-"){
         Result=NumEnter1 - NumEnter2;
         txtSonuc.setText(String.valueOf(Result));
     }
     else if(op=="*"){
         Result=NumEnter1 * NumEnter2;
         txtSonuc.setText(String.valueOf(Result));
     }
     else if(op=="/"){
         Result=NumEnter1 / NumEnter2;
         txtSonuc.setText(String.valueOf(Result));
     }
    }                                          

    private void btnToplamaActionPerformed(java.awt.event.ActionEvent evt) {                                           
     NumEnter1 = Double.parseDouble(txtSonuc.getText());
     txtSonuc.setText("");
     op="+";
    }                                          

    private void btnCikarmaActionPerformed(java.awt.event.ActionEvent evt) {                                           
     NumEnter1 = Double.parseDouble(txtSonuc.getText());
     txtSonuc.setText("");
     op="-";
    }                                          

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("5");
    }                                    

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("4");
    }                                    

    private void btnCarpmaActionPerformed(java.awt.event.ActionEvent evt) {                                          
     NumEnter1 = Double.parseDouble(txtSonuc.getText());
     txtSonuc.setText("");
     op="*";
    }                                         

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("3");
    }                                    

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        EnterNumbers("2");
    }                                    

    private void btnBolmeActionPerformed(java.awt.event.ActionEvent evt) {                                         
     NumEnter1 = Double.parseDouble(txtSonuc.getText());
     txtSonuc.setText("");
     op="/";
    }                                        

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {                                     
    txtSonuc.setText("");
    }                                    

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        EnterNumbers("00");
    }                                     

    private void btnNoktaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(! txtSonuc.getText().contains(",")){
            txtSonuc.setText(txtSonuc.getText() + btnNokta.getText() );
        }
    }                                        

    private void btnSilmeActionPerformed(java.awt.event.ActionEvent evt) {                                         
     String backSp=null;
     
     if(txtSonuc.getText().length()>0){
         StringBuilder ab=new StringBuilder(txtSonuc.getText());
         ab.deleteCharAt(txtSonuc.getText().length()-1);
         backSp=ab.toString();
         txtSonuc.setText(backSp);
     }
    }                                        

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {                                      
        txtSonuc.setText("");
        
        String Fn,Sn;
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn="";
        Sn="";
        
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBolme;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCarpma;
    private javax.swing.JButton btnCikarma;
    private javax.swing.JButton btnEsittir;
    private javax.swing.JButton btnNokta;
    private javax.swing.JButton btnSilme;
    private javax.swing.JButton btnToplama;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlScreen;
    private javax.swing.JTextField txtSonuc;
    // End of variables declaration                   
}

